### ISSUE TITLE
有没有6.x内核和ubuntu24适配的计划

### ISSUE THREAD

**Issue by qpzm1258** [CmST0us/tspi-linux-sdk#3]
有没有6.x内核和ubuntu24适配的计划，只能用旧版本的内核和rootfs吗？

**Comment by CmST0us** [comment]
有，我已经适配了6.1内核，还在测试

**Comment by CmST0us** [comment]
ubuntu 24现阶段不建议用，很多配套设施还没跟进

**Comment by qpzm1258** [comment]
坐等放出，要不debian bookworm也行，不过如果没有较新的再发行版本的话新内核意义不大。这破泰山派最大的问题就是没有一个比较方便交流的社区，有点后悔买了这玩意

**Comment by CmST0us** [comment]
野火他们的rootfs不错，我最近也在研究，还有一些otg的问题要处理。看起来可以移植过来。

如果你想用6.1的内核的话我倒是有一份，你可以先试试

**Comment by qpzm1258** [comment]
我之前也考虑野火的版本移植，或者armbian的仓库也有3588的Rockchip firmware的二进制bin文件，但是最终比较懒，放弃了

**Comment by CmST0us** [comment]
[https://github.com/CmST0us/tspi-kernel](https://github.com/CmST0us/tspi-kernel)
这个是泰山派yocto用的内核，可以直接替换掉这个sdk里kernel文件夹

另外想了解泰山派 yocto的话可以试试[https://github.com/CmST0us/tspi-yocto](https://github.com/CmST0us/tspi-yocto)

**Comment by qpzm1258** [comment]
有空学习下，谢谢大佬

**Comment by CmST0us** [comment]
有问题一起交流

**Comment by qpzm1258** [comment]
如果只能搞内核的话我考虑直接交叉编译算了，sdk太大了，开虚拟机占空间
