### ISSUE TITLE
是否可以适配Debian 11 或12 的编译

### ISSUE THREAD

**Issue by DeborahCox** [CmST0us/tspi-linux-sdk#5]
目前使用./build.sh debian会因为没有debian相关rootfs文件而中止，不知道如何操作可以适配编译debian 11呢

**Comment by CmST0us** [comment]
可以自己去制作debian的系统, 可以参考野火的rootfs.
这个仓库就不去维护了, git-lfs的储存成本比较高

**Comment by tuyaliang** [comment]
![IMG_6482](https://github.com/user-attachments/assets/1bc59a0c-c0e8-41a7-97c9-4557f5a29e51)
野火sdk编译的debian11
